version: "3.2"

services:
    php-apache2:
        build: .
        volumes:
            - ./:/var/www/html
#        expose:
#            - 9003
#            - 80
        extra_hosts:
                - 'host.docker.internal:host-gateway'
        ports:
            - "8000:80"
            - "9001:9003"
